### PR TITLE
Add conditional rosidl_generator_cpp in sensor_msgs

### PR DESCRIPTION
**Pull request by pablogs9**
Related: https://github.com/ros2/common_interfaces/pull/178#issuecomment-1076516076

CC: @sloretz

### CODE REVIEW

**Review by sloretz — COMMENTED** [review]
Opened PR to your branch with feedback: https://github.com/pablogs9/common_interfaces/pull/1

Edit: I did it wrong the first time, this PR targets your branch https://github.com/pablogs9/common_interfaces/pull/2

**Comment by pablogs9** [comment]
I manually moved the branch. Closing https://github.com/pablogs9/common_interfaces/pull/2.

Thanks a lot for this fix @sloretz!!

**Review by sloretz — APPROVED** [review]
LGTM with green CI 

Requires https://github.com/ros2/rosidl/pull/672

@pablogs9 the single typesupport case requires this bug fix too: https://github.com/ros2/rosidl_typesupport/pull/124

**Comment by gbiggs** [comment]
CI:

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/16438/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/11042/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/16806/)

**Pull request merged**
