### PR TITLE
disable many uncommonly used messages temporarly to save build time

### PR DESCRIPTION
**Pull request by wjwwood**
As we discussed on the mailing list.

The only thing I could think we might do differently is that we could add an option to opt-in or opt-out of building these messages using an environment variable. On the one hand that's a strange (surprising) side effect, but on the other we could re-enable these messages for the nightly/packaging jobs more easily.

### CODE REVIEW

**Comment by wjwwood** [comment]
Also, I left a few additional messages in (e.g. LaserScan and PointCloud* messages since I thought we might use them in the near future) and disabled some more in `std_msgs`, since it also has a lot of uncommonly used messages.

**Comment by dirk-thomas** [comment]
Can you please trigger a CI job for this to ensure that it works.

**Comment by wjwwood** [comment]
Yeah I will after I finish the local build.

**Comment by wjwwood** [comment]
Ok, it builds locally for me now, here is CI:

- http://ci.ros2.org/job/ci_linux/889/
- http://ci.ros2.org/job/ci_osx/742/
- http://ci.ros2.org/job/ci_windows/972/

**Comment by wjwwood** [comment]
I had tf2 disabled locally, trying again. I'll post CI links when they are actually passing.

**Comment by wjwwood** [comment]
Passing CI:

- http://ci.ros2.org/job/ci_linux/890/
- http://ci.ros2.org/job/ci_osx/743/
 - It has failing tests but they seem unrelated
- http://ci.ros2.org/job/ci_windows/973/
 - Also has unrelated test failures

Also I squashed the commits.

**Comment by dirk-thomas** [comment]
lgtm

**Pull request merged**
