### PR TITLE
enable some messages

### PR DESCRIPTION
**Pull request by gerkey**
These messages are needed for controlling the TurtleBot.

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by wjwwood** [comment]
+1 (but out of curiosity why do you need nav_msgs?)

**Comment by dirk-thomas** [comment]
Especially all messages and service of `nav_msgs`. Those should be restricted to what is actually needed.

**Comment by gerkey** [comment]
TurtleBot needs nav_msgs/Odometry. I commented out the other ones.

**Comment by wjwwood** [comment]
Thanks @gerkey, I believe it saves us a lot of build time by keeping the messages we aren't using commented out.

**Comment by mikaelarguedas** [comment]
I noticed that we never build/test the turtlebot demos on CI. Should we revert this PR to avoid generating/testing all these "unused" messages?

**Comment by dirk-thomas** [comment]
The question is do we expect anyone to build the turtlebot demo? If no, we can safely remove the message again. Otherwise I think it is more convenient to leave them enabled. We could still consider to not test them anymore?

**Comment by mikaelarguedas** [comment]
That is a good point, on the same idea the people who ported [turtlesim to ros2](https://github.com/sukha-cn/turtlesim-ros2) are using some messages that would end up not being generated anymore if we merge these. Closing them then. I have other ideas on how to reduce build/testing time and will open tickets accordingly

**Pull request merged**
