### PR TITLE
Update BatteryState.msg

### PR DESCRIPTION
**Pull request by borongyuan**
Add ternary lithium battery to power_supply_technology.

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
I'm not really familiar with battery chemistries in general, and ternary in particular.  Can you provide some links that talk about it?

**Review by gbiggs — APPROVED** [review]

**Comment by gbiggs** [comment]
@borongyuan Can you please add a short version of that explanation to the interface definition as a comment?

**Review by tfoote — COMMENTED** [review]
Adding this looks good, with some more documentation in the comments for clarity.

**Comment by borongyuan** [comment]
I have added definition for constants. Hope my understanding of the original contributor(@tfoote )'s definition is correct. I also added lead acid battery. Although this is an older, even somewhat outdated technology, it is still widely used.

**Review by clalancette — APPROVED** [review]
This looks good to me; thanks for adding the extra comments!

**Review by gbiggs — APPROVED** [review]

**Comment by gbiggs** [comment]
Thanks for the contribution!

**Pull request merged**
