### PR TITLE
[foxy] backport sensor_msgs_py

### PR DESCRIPTION
**Pull request by flynneva**

### CODE REVIEW

**Comment by flynneva** [comment]
@jacobperron @hidmic ready for review i think

**Comment by flynneva** [comment]
closes #142

**Comment by hidmic** [comment]
@flynneva it'd be best to cherry-pick the commits to be backported, so as to not lose the connection between both branch histories.

**Comment by flynneva** [comment]
@hidmic i think i did that right?

let me know if I should also cherry-pick the version changes as well - probably want different versions for foxy, no? I wasnt sure.

**Comment by hidmic** [comment]
> @hidmic i think i did that right?

Looks like it. Thanks.

>  probably want different versions for foxy

That's correct. And now I realize that the package version was set to match that of the other packages in `Rolling`. Bloom will not like that version discrepancy, and artificially downgrading this package seems wrong. @clalancette @jacobperron we don't have a policy for this, do we?

**Comment by clalancette** [comment]
> Yeah, that's unfortunate. I don't think we have precedence for something like this. 

Yeah, this is the first time I can remember this issue coming up.

> Moving it to it's own repo would solve the issue, but perhaps that's a bit drastic. Downgrading the version to match the other packages in this repo wouldn't be the end of the world. I'm open to other suggestions.

I wouldn't put this in a separate repository; at least, we had that discussion when this PR first came in, and we decided to keep it here.  While downgrading the version is a bit weird, I don't see why it wouldn't work.  Also, since the foxy and the master branch will never be recombined, I don't see any conflicts arising from it in the future.  Finally, by setting the version number back for Foxy, it maintains the monotonically increasing property of the version numbers (that is, the version number in Foxy will be strictly less than the version number in Rolling/Galactic).  So I'll suggest we just set it back.

**Comment by flynneva** [comment]
so would setting it to match the current foxy `sensor_msgs` version make sense then?

`2.0.3` i think.

**Comment by hidmic** [comment]
> so would setting it to match the current foxy sensor_msgs version make sense then?

> 2.0.3 i think.

That's right @flynneva.

**Comment by tfoote** [comment]
Process note: Downgrading the version if it has not been released is sub optimal for introspection/discoverability/communication. However if it has already been released we can't do it, because the older higher version will take precedence if already installed or cached anywhere in the release pipeline. I think we're in the first case so this is probably ok.

**Comment by clalancette** [comment]
> Process note: Downgrading the version if it has not been released is sub optimal for introspection/discoverability/communication. However if it has already been released we can't do it, because the older higher version will take precedence if already installed or cached anywhere in the release pipeline. I think we're in the first case so this is probably ok.

In this particular case, this is two different release streams.  That is, we've already released this package as `ros-rolling-sensor-msgs-py 2.2.1`.  This PR is backporting it to Foxy, where it will be released as `ros-foxy-sensor-msgs-py 2.0.3` (well, it will probably get bumped for the release, but you get my point).  Since we don't have a foxy -> {rolling,galactic} direct upgrade path, they are on different streams essentially forever.  Thus, I don't think there are any apt problems we need to worry about.

Also, the number in Foxy (2.0.3) will be lower than that in Rolling/Galactic (2.2.1), so there should be no "head-scratching" about the version numbers.

**Comment by flynneva** [comment]
so......can we merge this thing? 😄

**Comment by hidmic** [comment]
Not before CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13975/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8806/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11675/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14058/)

**Review by jacobperron — APPROVED** [review]

**Comment by jacobperron** [comment]
Windows warnings are unrelated.

**Comment by flynneva** [comment]
@jacobperron is there anything else needed to get this released to foxy - or will this now be included in some sort of automated release for the entire 'common_interfaces' repo?

**Comment by jacobperron** [comment]
@flynneva A maintainer should make a release for Foxy for it to be included in the next sync.

I will make sure it get's released before the next patch release (there's not tentative date for it, but I will try to do one within a few weeks from now).

**Comment by flynneva** [comment]
@jacobperron  no rush! but good to know. thanks again for everyone's effort on this, really appreciated 😄

**Pull request merged**
