### PR TITLE
Removed TODO

### PR DESCRIPTION
**Pull request by ahcorde**
There is a TODO that mentioned the adition of this message. Happy to remove the comment and the new message if this is not required anymore

There is already a service called GetMap.srv

@SteveMacenski, @tfoote  ?

### CODE REVIEW

**Comment by SteveMacenski** [comment]
This seems like a weird action, I think a service is the most appropriate interface - but I suppose it doesn't _hurt_. Has anyone been requesting this?

**Comment by ahcorde** [comment]
Nope, I just saw the TODO

**Comment by SteveMacenski** [comment]
My feedback is "lets just remove the TODO and see if anyone cares" since it doesn't seem that anyone has until now. But, hey, on the other hand, its not hurting anyone.

**Comment by clalancette** [comment]
> My feedback is "lets just remove the TODO and see if anyone cares" since it doesn't seem that anyone has until now. But, hey, on the other hand, its not hurting anyone to add the new action.

I'd be more for removing the TODO.  We shouldn't add things in that don't have users, in my opinion.

**Comment by tfoote** [comment]
Thanks for finding the TODO and reviewing it. But I think that the GetMap action doesn't add a lot of value on top of the GetMap Service so as there's no demand we might as well not add it and keep things simpler.

**Review by tfoote — CHANGES_REQUESTED** [review]
Without feedback this doesn't add anything on top of the service. And we now have async service clients so that's not a benefit anymore either.

**Review by tfoote — APPROVED** [review]
Thanks for cleaning this up!

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20858/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15161/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21544/)

**Pull request merged**
