### PR TITLE
Create new messages with all fields needed to define a velocity and transform it 

### PR DESCRIPTION
**Pull request by ahcorde**
Hi @destogl,

I superseed this other PR https://github.com/ros2/common_interfaces/pull/233 We want to merge this in before feature freeze which I believe it's in two weeks.

### CODE REVIEW

**Review by tfoote — COMMENTED** [review]
Thanks for pulling this all together @ahcorde I think that this gets us to a moderately compact message which I think has clear semantics. 

Is https://github.com/ros2/geometry2/pull/646 up to date with this?

**Comment by tfoote** [comment]
@destogl @SteveMacenski @azeey Can you take a look at this updated version of #233 ? It would be really valuable to get this finalized this week.

**Comment by ahcorde** [comment]
> Is [ros2/geometry2#646](https://github.com/ros2/geometry2/pull/646) up to date with this?

@tfoote, yes, it's up to date

**Review by tfoote — APPROVED** [review]
With a test implementation available in https://github.com/ros2/geometry2/pull/646

And running CI against the union of these two: 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20805/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15108/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21489/)

This now looks ready to go.

**Comment by ahcorde** [comment]
warnings are in the other PR, merging this one

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport humble iron

**Comment by ahcorde** [comment]
There is a request to backport this feature in [geometry2](https://github.com/ros2/geometry2/pull/646#issuecomment-2120698526). This is a new message, it's fine to backport this to `humble` and `iron`.

**Pull request merged**
