### PR TITLE
Fix formatting in sensor_msgs_py

### PR DESCRIPTION
**Pull request by christophebedard**

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Seems reasonable to me with green CI.

Out of curiosity, how did you notice these?  And why didn't they get picked up by our linters in here?

**Comment by christophebedard** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21074/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15378/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21792/)

**Review by tfoote — APPROVED** [review]
Thanks for the cleanup. It's odd to have snuck through for this long.

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Pull request merged**
