### PR TITLE
Add support for non standard point step sizes

### LINKED ISSUE #197: [sensor_msgs_py] Missing handling of point_step value in PointCloud2 message in read_points() fcn
## Bug report

In [sensor_msgs_py/sensor_msgs_py/point_cloud2.py](https://github.com/ros2/common_interfaces/tree/rolling/sensor_msgs_py/sensor_msgs_py/point_cloud2.py) is missing handling of point_step value from PointCloud2 message when reading the PC2 points (read_points()). Numpy dtype is automatically generated based on PointFields including the itemsize value. The end of the point (point_step) is expected just after the last item in the array. When the point_step is actually greater, the dtype is incorrectly aligned with the data array. 

- Operating System:
  - Ubuntu 20.04
- Version or commit hash:
  - ROS2 Humble
- Package
  - sensor_msgs_py v4.2 or later

#### PointCloud2 message:
```Python
>>>print(pc_msg)
sensor_msgs.msg.PointCloud2(header=std_msgs.msg.Header(
stamp=builtin_interfaces.msg.Time(sec=1658393524, nanosec=629456477),
frame_id='tst_frame'), 
height=1, width=65, fields=[
sensor_msgs.msg.PointField(name='x', offset=0, datatype=7, count=1),
sensor_msgs.msg.PointField(name='y', offset=4, datatype=7, count=1),
sensor_msgs.msg.PointField(name='z', offset=8, datatype=7, count=1),
sensor_msgs.msg.PointField(name='normal_x', offset=16, datatype=7, count=1),
sensor_msgs.msg.PointField(name='normal_y', offset=20, datatype=7, count=1),
sensor_msgs.msg.PointField(name='normal_z', offset=24, datatype=7, count=1),
sensor_msgs.msg.PointField(name='curvature', offset=32, datatype=7, count=1)],
is_bigendian=False, point_step=48, row_step=3120, data=[124, ...], is_dense=False)
```
#### Resulting dtype:
```Python
>>>print(points.dtype)
{'names':['x','y','z','normal_x','normal_y','normal_z','curvature'],
'formats':['<f4','<f4','<f4','<f4','<f4','<f4','<f4'], 'offsets':[0,4,8,16,20,24,32],
'itemsize':36}
```
#### Correct dtype:
```Python
>>>print(points.dtype)
{'names':['x','y','z','normal_x','normal_y','normal_z','curvature'],
'formats':['<f4','<f4','<f4','<f4','<f4','<f4','<f4'], 'offsets':[0,4,8,16,20,24,32],
'itemsize':48}
```

### PR DESCRIPTION
**Pull request by Flova**
Fixes #197

### CODE REVIEW

**Comment by gbiggs** [comment]
Thanks for the fix! Could you please add a test to [the tests file](https://github.com/ros2/common_interfaces/blob/rolling/sensor_msgs_py/test/test_point_cloud2.py) that verifies this does fix the issue?

**Comment by Flova** [comment]
Thanks for your quick response @gbiggs! I added the test it seems to solve the issue.

**Review by gbiggs — APPROVED** [review]

**Comment by gbiggs** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17061/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11623/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17488/)

**Comment by Flova** [comment]
Do you have an idea what's causing the tests to fail? The option manager traceback seems unrelated to the changes from this or.

**Comment by clalancette** [comment]
> Do you have an idea what's causing the tests to fail? The option manager traceback seems unrelated to the changes from this or.

That's a separate issue that we are addressing in https://github.com/ros2/ci/pull/675

**Comment by Flova** [comment]
Okay :+1:

**Comment by gbiggs** [comment]
Another CI run:

- Linux [Build Status](https://ci.ros2.org/job/ci_linux/17137/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/11684/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/17556/)

**Comment by gbiggs** [comment]
Thanks for the contribution!

**Pull request merged**
