### PR TITLE
delete AMENT_IGNORE in diagnostics_msgs

### PR DESCRIPTION
**Pull request by codebot**
The messages in this package are needed for the joy node.

### CODE REVIEW

**Comment by gerkey** [comment]
+1

**Comment by gerkey** [comment]
Found a bug in the Python generator. We also need ros2/rosidl#116.

**Comment by gerkey** [comment]
CI:

* http://ci.ros2.org/job/ci_linux/1190/
* http://ci.ros2.org/job/ci_osx/966/
* http://ci.ros2.org/job/ci_windows/1244/

**Comment by gerkey** [comment]
New CI, following rename of package:

* http://ci.ros2.org/job/ci_linux/1191/
* http://ci.ros2.org/job/ci_osx/967/
* http://ci.ros2.org/job/ci_windows/1245/

**Comment by gerkey** [comment]
Mysterious rclpy test failures plus a broken build on Windows. Investigating.

**Comment by gerkey** [comment]
The OSX test failures related to Python and `rmw_connext_cpp` also occur when building from master:

http://ci.ros2.org/job/ci_osx/968/testReport/

So I think that we're OK on the front with this change.

But the use of `ERROR` as a message field is causing the Windows build to fail.

**Comment by gerkey** [comment]
With https://github.com/ros2/rosidl/pull/116/commits/d4264b70387e91b8f46a40ff307881f28ff07c04, the Windows build doesn't fail. And the test failures look to me like they're unrelated:

http://ci.ros2.org/job/ci_windows/1249/testReport/

**Comment by gerkey** [comment]
Somebody else should +1 the package rename that I did here.

**Comment by wjwwood** [comment]
Oops, that's probably my fault. +1

**Comment by gerkey** [comment]
forgot to squash; apologies to people in the future who read the commit history

**Pull request merged**
